- name: Create Jenkins job to run periodically
  hosts: jenkins
  become: yes
  vars:
    jenkins_url: http://192.168.150.154:8080
    jenkins_user: jenkins
    jenkins_password: root
    job_name: period
    job_config_template: job_config.xml.j2
  tasks:
    - name: Install pip if not already installed
      apt:
        name: python3-pip
        state: present
      become: yes

    - name: Install Jenkins module for Ansible
      pip:
        name: jenkins
        state: present
      become: yes

    - name: Create Jenkins job
      jenkins_job:
        config: "{{ lookup('template', 'templates/' ~ job_config_template) }}"
        name: "{{ job_name }}"
        user: "{{ jenkins_user }}"
        password: "{{ jenkins_password }}"
        url: "{{ jenkins_url }}"
      delegate_to: localhost
